; PicoQuant device configuration. Channel_0 is physical CH1.
[Device]
SyncDiv = 1
SyncEdgeTrig = -170,1
SyncChannelEnable = 1
SyncChannelOffset = 0
Offset = 0
TriggerOutput = 0

[Channel_0]
EdgeTrig = -170,1
ChanOffs = 0
ChanEna = 1
